# Generated by Django 5.1.7 on 2025-03-27 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceCategoriy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_desc', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('googlMapLink', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='imagesP/')),
                ('long_desc', models.TextField()),
                ('kids', models.IntegerField(null=True)),
                ('photography', models.BooleanField(null=True)),
                ('art', models.BooleanField(null=True)),
                ('sports', models.BooleanField(null=True)),
                ('events', models.BooleanField(null=True)),
                ('quiet', models.BooleanField(null=True)),
                ('crowded', models.BooleanField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.placecategoriy')),
            ],
        ),
    ]
